
{{- $serviceName := include "v2t-list.serviceName" . -}}
{{- $namePrefix := include "v2t-list.namePrefix" . -}}
{{- $name := include "v2t-list.name" . -}}

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{$name}}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
spec:
  rules:
    - http:
        paths:
          - path: {{ .Values.ingress.path | default "/" }}
            backend:
              serviceName: {{$name}}
              servicePort: 80
{{- if $namePrefix }}
      host: {{ $namePrefix }}{{ .Values.ingress.host }}
{{- else }}
      host: {{ .Values.ingress.host }}
{{- end }}
