{{- $name := include "v2t-list.name" . -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{$name}}
  labels:
    app: {{$name}}
spec:
  ports:
  - name: http-port
    port: 80
    targetPort: 80
  selector:
    app: {{$name}}
